version: "3"
services:
    node_app:
        container_name: node_app
        restart: always
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        ports:
            - "8000:8000"
        links:
            - mongo_db
        depends_on:
            - mongo_db
    mongo_db:
        container_name: mongo_db
        image: mongo:latest
        volumes:
            - /data/db
            - /data/configdb
        restart: always
        ports:
            - "27017:27017"